<script>
  import { searchResults, loading, error, setLoading, setError, addToCart } from '../lib/stores.js';
  import { onMount } from 'svelte';
  import { calculateROI as sharedCalculateROI } from '../lib/roi.js';

  let searchTerm = '';
  let addressSearch = '';
  let addressSearching = false;
  let allStores = [];
  let filtered = [];
  let useGeolocation = false;
  let userLocation = null;
  let storeCycleFilter = 'all';

  // Multilingual pricing sheet export
  const TRANSLATIONS = {
    en: { title: 'Advertising Investment Summary', store: 'Store', address: 'Address', adType: 'Ad Type', cases: 'Cases', impressions: 'Estimated Impressions', daily: 'Daily', monthly: 'Monthly', annual: 'Annual', paymentPlans: 'Payment Plans', plan: 'Plan', payments: 'payments', perMonth: '/month', total: 'Total', dailyInvestment: 'Daily Investment', bestDeal: 'Best Deal — Save 15%', onePayment: 'One payment', save: 'Save', formula: 'cases × 50 rolls × 137 segments × 2 prints × 4 quarters', poweredBy: 'Generated by imPro Sales Portal — IndoorMedia', yourAd: 'Your ad reaches every customer at checkout — 100% visibility, every transaction.' },
    es: { title: 'Resumen de Inversión Publicitaria', store: 'Tienda', address: 'Dirección', adType: 'Tipo de Anuncio', cases: 'Cajas', impressions: 'Impresiones Estimadas', daily: 'Diario', monthly: 'Mensual', annual: 'Anual', paymentPlans: 'Planes de Pago', plan: 'Plan', payments: 'pagos', perMonth: '/mes', total: 'Total', dailyInvestment: 'Inversión Diaria', bestDeal: 'Mejor Oferta — Ahorre 15%', onePayment: 'Un solo pago', save: 'Ahorre', formula: 'cajas × 50 rollos × 137 segmentos × 2 impresiones × 4 trimestres', poweredBy: 'Generado por imPro Sales Portal — IndoorMedia', yourAd: 'Su anuncio llega a cada cliente en la caja — 100% visibilidad, cada transacción.' },
    zh: { title: '广告投资摘要', store: '商店', address: '地址', adType: '广告类型', cases: '收银台数量', impressions: '预估曝光量', daily: '每日', monthly: '每月', annual: '每年', paymentPlans: '付款方案', plan: '方案', payments: '期', perMonth: '/月', total: '总计', dailyInvestment: '每日投资', bestDeal: '最优惠 — 节省15%', onePayment: '一次付清', save: '节省', formula: '箱 × 50卷 × 137段 × 2次印刷 × 4季度', poweredBy: '由imPro销售平台生成 — IndoorMedia', yourAd: '您的广告触达每一位结账顾客 — 100%可见率，每笔交易。' },
    vi: { title: 'Tóm Tắt Đầu Tư Quảng Cáo', store: 'Cửa hàng', address: 'Địa chỉ', adType: 'Loại quảng cáo', cases: 'Quầy tính tiền', impressions: 'Lượt hiển thị ước tính', daily: 'Hàng ngày', monthly: 'Hàng tháng', annual: 'Hàng năm', paymentPlans: 'Các gói thanh toán', plan: 'Gói', payments: 'kỳ', perMonth: '/tháng', total: 'Tổng', dailyInvestment: 'Đầu tư hàng ngày', bestDeal: 'Ưu đãi tốt nhất — Tiết kiệm 15%', onePayment: 'Thanh toán một lần', save: 'Tiết kiệm', formula: 'hộp × 50 cuộn × 137 đoạn × 2 lần in × 4 quý', poweredBy: 'Tạo bởi imPro Sales Portal — IndoorMedia', yourAd: 'Quảng cáo của bạn tiếp cận mọi khách hàng tại quầy thanh toán — 100% hiển thị, mọi giao dịch.' },
    tl: { title: 'Buod ng Pamumuhunan sa Advertising', store: 'Tindahan', address: 'Address', adType: 'Uri ng Ad', cases: 'Mga Kaha', impressions: 'Tinatayang Impressions', daily: 'Araw-araw', monthly: 'Buwan-buwan', annual: 'Taun-taon', paymentPlans: 'Mga Plano sa Pagbabayad', plan: 'Plano', payments: 'bayad', perMonth: '/buwan', total: 'Kabuuan', dailyInvestment: 'Pang-araw-araw na Puhunan', bestDeal: 'Pinakamahusay — Save 15%', onePayment: 'Isang bayad', save: 'Tipid', formula: 'kahon × 50 rolyo × 137 segment × 2 print × 4 quarter', poweredBy: 'Ginawa ng imPro Sales Portal — IndoorMedia', yourAd: 'Ang iyong ad ay nakikita ng bawat customer sa checkout — 100% visibility, bawat transaksyon.' },
    ko: { title: '광고 투자 요약', store: '매장', address: '주소', adType: '광고 유형', cases: '계산대 수', impressions: '예상 노출수', daily: '일일', monthly: '월간', annual: '연간', paymentPlans: '결제 플랜', plan: '플랜', payments: '회', perMonth: '/월', total: '합계', dailyInvestment: '일일 투자', bestDeal: '최고 할인 — 15% 절약', onePayment: '일시불', save: '절약', formula: '케이스 × 50롤 × 137구간 × 2회인쇄 × 4분기', poweredBy: 'imPro Sales Portal 생성 — IndoorMedia', yourAd: '귀하의 광고는 계산대의 모든 고객에게 도달합니다 — 100% 가시성, 모든 거래.' }
  };

  // Strip emoji and non-WinAnsi characters for PDF text
  function pdfSafe(str) {
    return (str || '').replace(/[\u{1F000}-\u{1FFFF}|\u{2600}-\u{27BF}|\u{FE00}-\u{FE0F}|\u{200D}|\u{20E3}|\u{E0020}-\u{E007F}]/gu, '').replace(/[^\x00-\xFF]/g, '').trim();
  }

  // Check if language needs Unicode (CJK/Korean)
  function needsUnicode(lang) { return ['zh', 'ko', 'vi', 'tl'].includes(lang); }

  async function exportPricingSheet(store, pricing, adType, lang) {
    // For non-Latin languages, export as HTML (handles Unicode natively)
    if (needsUnicode(lang)) {
      return exportPricingSheetHTML(store, pricing, adType, lang);
    }
    try {
    const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib');
    const t = TRANSLATIONS[lang] || TRANSLATIONS.en;
    const doc = await PDFDocument.create();
    const regular = await doc.embedFont(StandardFonts.Helvetica);
    const bold = await doc.embedFont(StandardFonts.HelveticaBold);
    const pageW = 612; const pageH = 792; const margin = 50;
    const page = doc.addPage([pageW, pageH]);
    let y = pageH - margin;
    const maxW = pageW - margin * 2;

    // Header
    page.drawRectangle({ x: 0, y: pageH - 85, width: pageW, height: 85, color: rgb(0.8, 0, 0) });
    page.drawText('IndoorMedia', { x: margin, y: pageH - 35, size: 24, font: bold, color: rgb(1, 1, 1) });
    page.drawText(t.title, { x: margin, y: pageH - 55, size: 13, font: regular, color: rgb(1, 0.9, 0.9) });
    page.drawText(new Date().toLocaleDateString(), { x: pageW - margin - 80, y: pageH - 35, size: 10, font: regular, color: rgb(1, 0.9, 0.9) });
    y = pageH - 105;

    // Store info
    const caseCount = parseInt(store['Case Count']) || 0;
    const annualImp = caseCount * 50 * 137 * 2 * 4;
    const monthlyImp = Math.round(annualImp / 12);
    const dailyImp = Math.round(annualImp / 365);

    function line(label, value, isBold) {
      page.drawText(pdfSafe(label), { x: margin, y, size: 11, font: bold, color: rgb(0.3, 0.3, 0.3) });
      page.drawText(pdfSafe(value), { x: margin + 140, y, size: 11, font: isBold ? bold : regular, color: rgb(0.1, 0.1, 0.1) });
      y -= 18;
    }

    line(t.store + ':', `${store.GroceryChain} — ${store.StoreName}`);
    line(t.address + ':', `${store.Address}, ${store.City}, ${store.State} ${store.PostalCode}`);
    line(t.adType + ':', adType === 'double' ? 'Double Ad' : 'Single Ad');
    line(t.cases + ':', String(caseCount));
    y -= 8;

    // Impressions box
    page.drawRectangle({ x: margin, y: y - 50, width: maxW, height: 60, color: rgb(0.95, 0.97, 1), borderColor: rgb(0.08, 0.39, 0.75), borderWidth: 1 });
    page.drawText(pdfSafe(`${t.impressions}`), { x: margin + 10, y: y - 5, size: 12, font: bold, color: rgb(0.08, 0.39, 0.75) });
    page.drawText(`${t.daily}: ${dailyImp.toLocaleString()}`, { x: margin + 10, y: y - 22, size: 10, font: regular, color: rgb(0.2, 0.2, 0.2) });
    page.drawText(`${t.monthly}: ${monthlyImp.toLocaleString()}`, { x: margin + 180, y: y - 22, size: 10, font: regular, color: rgb(0.2, 0.2, 0.2) });
    page.drawText(`${t.annual}: ${annualImp.toLocaleString()}`, { x: margin + 350, y: y - 22, size: 11, font: bold, color: rgb(0.08, 0.39, 0.75) });
    page.drawText(`(${caseCount} ${t.formula})`, { x: margin + 10, y: y - 38, size: 8, font: regular, color: rgb(0.5, 0.5, 0.5) });
    y -= 70;

    // Value prop
    page.drawText(pdfSafe(t.yourAd), { x: margin, y, size: 10, font: regular, color: rgb(0.4, 0.4, 0.4) });
    y -= 25;

    // Payment plans table
    page.drawText(pdfSafe(t.paymentPlans), { x: margin, y, size: 14, font: bold, color: rgb(0.1, 0.1, 0.1) });
    y -= 25;

    // Table header
    page.drawRectangle({ x: margin, y: y - 2, width: maxW, height: 20, color: rgb(0.95, 0.95, 0.95) });
    page.drawText(pdfSafe(t.plan), { x: margin + 5, y: y + 2, size: 9, font: bold, color: rgb(0.3, 0.3, 0.3) });
    page.drawText('Payment', { x: margin + 155, y: y + 2, size: 9, font: bold, color: rgb(0.3, 0.3, 0.3) });
    page.drawText(pdfSafe(t.total), { x: margin + 270, y: y + 2, size: 9, font: bold, color: rgb(0.3, 0.3, 0.3) });
    page.drawText(pdfSafe(t.dailyInvestment), { x: margin + 380, y: y + 2, size: 9, font: bold, color: rgb(0.3, 0.3, 0.3) });
    y -= 22;

    const plans = [
      { name: `Monthly (12 ${t.payments})`, payment: `$${pricing.monthly}/mo`, total: pricing.monthlyTotal, daily: (parseFloat(pricing.monthlyTotal) / 365).toFixed(2) },
      { name: `3-Month (3 ${t.payments}) - 10% off`, payment: `$${pricing.threeMonth} x 3`, total: pricing.threeMonthTotal, daily: (parseFloat(pricing.threeMonthTotal) / 365).toFixed(2) },
      { name: `6-Month (6 ${t.payments}) - 7.5% off`, payment: `$${pricing.sixMonth} x 6`, total: pricing.sixMonthTotal, daily: (parseFloat(pricing.sixMonthTotal) / 365).toFixed(2) },
      { name: `Paid in Full - 15% off`, payment: `$${pricing.pif}`, total: pricing.pif, daily: (parseFloat(pricing.pif) / 365).toFixed(2) },
    ];

    plans.forEach((p, i) => {
      const isLast = i === plans.length - 1;
      if (isLast) {
        page.drawRectangle({ x: margin, y: y - 4, width: maxW, height: 22, color: rgb(0.91, 0.96, 0.91) });
      }
      page.drawText(pdfSafe(p.name), { x: margin + 5, y, size: 9, font: isLast ? bold : regular, color: rgb(0.1, 0.1, 0.1) });
      page.drawText(pdfSafe(p.payment), { x: margin + 155, y, size: 9, font: regular, color: rgb(0.3, 0.3, 0.3) });
      page.drawText(`$${p.total}`, { x: margin + 270, y, size: 9, font: bold, color: rgb(0.1, 0.1, 0.1) });
      page.drawText(`$${p.daily}/day`, { x: margin + 380, y, size: 9, font: regular, color: rgb(0.18, 0.49, 0.2) });
      y -= 24;
    });

    y -= 10;
    page.drawText(`${t.save}: $${pricing.savings}`, { x: margin, y, size: 11, font: bold, color: rgb(0.18, 0.49, 0.2) });
    y -= 30;

    // Footer
    page.drawLine({ start: { x: margin, y }, end: { x: pageW - margin, y }, thickness: 0.5, color: rgb(0.8, 0.8, 0.8) });
    y -= 15;
    page.drawText(pdfSafe(t.poweredBy), { x: margin, y, size: 8, font: regular, color: rgb(0.5, 0.5, 0.5) });

    const bytes = await doc.save();
    const blob = new Blob([bytes], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const langSuffix = lang !== 'en' ? ` (${lang.toUpperCase()})` : '';
    const filename = `Pricing - ${store.GroceryChain} ${store.City}${langSuffix}.pdf`;
    
    // iOS Safari needs window.open for blob PDFs
    if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
      window.open(url, '_blank');
    } else {
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
    setTimeout(() => URL.revokeObjectURL(url), 10000);
    } catch (err) {
      console.error('PDF export error:', err);
      alert('❌ Error generating PDF: ' + err.message);
    }
  }

  // HTML export for CJK/Unicode languages
  function exportPricingSheetHTML(store, pricing, adType, lang) {
    const t = TRANSLATIONS[lang] || TRANSLATIONS.en;
    const caseCount = parseInt(store['Case Count']) || 0;
    const annualImp = caseCount * 50 * 137 * 2 * 4;
    const monthlyImp = Math.round(annualImp / 12);
    const dailyImp = Math.round(annualImp / 365);

    const plans = [
      { name: `${t.monthly} (12 ${t.payments})`, payment: `$${pricing.monthly}/${t.monthly.toLowerCase().slice(0,2)}`, total: pricing.monthlyTotal, daily: (parseFloat(pricing.monthlyTotal) / 365).toFixed(2) },
      { name: `3-${t.monthly} (3 ${t.payments}) — ${t.save} 10%`, payment: `$${pricing.threeMonth} x 3`, total: pricing.threeMonthTotal, daily: (parseFloat(pricing.threeMonthTotal) / 365).toFixed(2) },
      { name: `6-${t.monthly} (6 ${t.payments}) — ${t.save} 7.5%`, payment: `$${pricing.sixMonth} x 6`, total: pricing.sixMonthTotal, daily: (parseFloat(pricing.sixMonthTotal) / 365).toFixed(2) },
      { name: `⭐ ${t.onePayment} — ${t.save} 15%`, payment: `$${pricing.pif}`, total: pricing.pif, daily: (parseFloat(pricing.pif) / 365).toFixed(2) },
    ];

    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${t.title} — ${store.GroceryChain} ${store.City}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:16px;background:#fff}
.header{background:linear-gradient(135deg,#CC0000,#8B0000);color:#fff;padding:20px;border-radius:12px;margin-bottom:20px;text-align:center}
.header h1{font-size:22px;margin-bottom:4px}.header p{font-size:13px;opacity:.9}
.info{margin-bottom:16px;font-size:14px}.info div{padding:6px 0;border-bottom:1px solid #eee}
.info strong{display:inline-block;width:100px;color:#666}
.imp{background:linear-gradient(135deg,#E3F2FD,#F3E5F5);border:1px solid #1565C0;border-radius:12px;padding:16px;margin-bottom:16px;text-align:center}
.imp h3{color:#1565C0;margin-bottom:10px}.imp-grid{display:flex;gap:8px}
.imp-stat{flex:1;background:rgba(255,255,255,.8);border-radius:8px;padding:10px 4px;text-align:center}
.imp-stat.hl{background:#1565C0;color:#fff}.imp-val{font-size:18px;font-weight:800;display:block}
.imp-lbl{font-size:10px;text-transform:uppercase;color:#666}.imp-stat.hl .imp-lbl{color:rgba(255,255,255,.8)}
table{width:100%;border-collapse:collapse;margin-bottom:16px}th{background:#f5f5f5;text-align:left;padding:8px;font-size:11px;color:#666}
td{padding:8px;border-bottom:1px solid #eee;font-size:12px}.best{background:#E8F5E9}
.daily{color:#2E7D32;font-weight:700}.save{color:#2E7D32;font-weight:800;font-size:14px;margin:12px 0}
.vp{font-size:13px;color:#555;font-style:italic;margin-bottom:16px;padding:12px;background:#f9f9f9;border-radius:8px}
.footer{font-size:10px;color:#999;text-align:center;margin-top:20px;border-top:1px solid #eee;padding-top:10px}
@media print{body{padding:0}.header{border-radius:0}}
</style></head><body>
<div class="header"><h1>IndoorMedia</h1><p>${t.title}</p><p>${new Date().toLocaleDateString()}</p></div>
<div class="info">
<div><strong>${t.store}:</strong> ${store.GroceryChain} — ${store.StoreName}</div>
<div><strong>${t.address}:</strong> ${store.Address}, ${store.City}, ${store.State} ${store.PostalCode}</div>
<div><strong>${t.adType}:</strong> ${adType === 'double' ? 'Double Ad' : 'Single Ad'}</div>
<div><strong>${t.cases}:</strong> ${caseCount}</div>
</div>
<div class="imp"><h3>👁️ ${t.impressions}</h3>
<div class="imp-grid">
<div class="imp-stat"><span class="imp-val">${dailyImp.toLocaleString()}</span><span class="imp-lbl">${t.daily}</span></div>
<div class="imp-stat"><span class="imp-val">${monthlyImp.toLocaleString()}</span><span class="imp-lbl">${t.monthly}</span></div>
<div class="imp-stat hl"><span class="imp-val">${annualImp.toLocaleString()}</span><span class="imp-lbl">${t.annual}</span></div>
</div></div>
<div class="vp">${t.yourAd}</div>
<table><thead><tr><th>${t.plan}</th><th>Payment</th><th>${t.total}</th><th>${t.dailyInvestment}</th></tr></thead><tbody>
${plans.map((p, i) => `<tr class="${i === plans.length - 1 ? 'best' : ''}"><td>${p.name}</td><td>${p.payment}</td><td><strong>$${p.total}</strong></td><td class="daily">$${p.daily}/${t.daily.toLowerCase()}</td></tr>`).join('')}
</tbody></table>
<div class="save">${t.save}: $${pricing.savings}</div>
<div class="footer">${t.poweredBy}</div>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  }

  // Store phone number lookup (cached)
  let storePhones = {};
  const PLACES_KEY = 'AIzaSyBoslNJj8aO6wkQOfkH9e4qTVJZ-G9nOuA';
  
  async function lookupStorePhone(store) {
    const key = store.StoreName;
    if (storePhones[key] !== undefined) return; // already looked up or in progress
    storePhones[key] = 'loading';
    storePhones = storePhones; // trigger reactivity
    try {
      const query = `${store.GroceryChain} ${store.Address} ${store.City} ${store.State}`;
      const res = await fetch('https://places.googleapis.com/v1/places:searchText', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Goog-Api-Key': PLACES_KEY,
          'X-Goog-FieldMask': 'places.nationalPhoneNumber,places.internationalPhoneNumber' },
        body: JSON.stringify({ textQuery: query, maxResultCount: 1 })
      });
      const data = await res.json();
      const phone = data.places?.[0]?.nationalPhoneNumber || data.places?.[0]?.internationalPhoneNumber || '';
      storePhones[key] = phone;
      storePhones = storePhones;
    } catch { storePhones[key] = ''; storePhones = storePhones; }
  }

  // ROI Calculator state
  let roiStore = null;
  let roiInvestment = '0';
  let roiAvgSpend = 50;
  let roiNewCustomers = 10;
  let roiVisitsPerYear = 12;
  let roiCouponDiscount = 0;
  let roiTotalRedemptions = 0;
  let roiCOGS = 0;

  function showROI(totalPrice, store) {
    roiStore = store.StoreName;
    roiInvestment = String(totalPrice).replace('$', '').replace(',', '');
    roiAvgSpend = 50;
    roiNewCustomers = 10;
    roiVisitsPerYear = 12;
    roiCouponDiscount = 0;
    roiTotalRedemptions = 0;
    roiCOGS = 0;
  }

  const ROI_TRANSLATIONS = {
    en: { title: 'ROI Analysis Report', inputs: 'Inputs', investment: 'Investment', avgSpend: 'Avg Customer Spend', newCust: 'New Customers / Month', visits: 'Visits / Year', discount: 'Avg Discount per Coupon', redemptions: 'Monthly Coupon Redemptions', cogs: 'Cost of Goods Sold', revenue: 'Revenue Analysis', monthlyRev: 'Monthly Revenue (New Customers)', grossAnnual: 'Gross Annual Revenue', cogsLabel: 'Cost of Goods Sold', netAnnual: 'Net Annual Revenue', annualRedemptions: 'Annual Redemptions', couponRev: 'Coupon Redemption Revenue', couponCost: 'Coupon Discount Cost', results: 'Results', roi: 'Return on Investment', netProfit: 'Net Profit', generated: 'Generated', registerTape: 'Register Tape Advertising', printSave: 'Print / Save as PDF' },
    es: { title: 'Informe de Análisis ROI', inputs: 'Datos', investment: 'Inversión', avgSpend: 'Gasto Promedio del Cliente', newCust: 'Nuevos Clientes / Mes', visits: 'Visitas / Año', discount: 'Descuento Promedio por Cupón', redemptions: 'Canjes de Cupones Mensuales', cogs: 'Costo de Bienes Vendidos', revenue: 'Análisis de Ingresos', monthlyRev: 'Ingresos Mensuales (Nuevos Clientes)', grossAnnual: 'Ingresos Brutos Anuales', cogsLabel: 'Costo de Bienes Vendidos', netAnnual: 'Ingresos Netos Anuales', annualRedemptions: 'Canjes Anuales', couponRev: 'Ingresos por Cupones', couponCost: 'Costo de Descuento por Cupones', results: 'Resultados', roi: 'Retorno de Inversión', netProfit: 'Ganancia Neta', generated: 'Generado', registerTape: 'Publicidad en Cinta de Caja', printSave: 'Imprimir / Guardar como PDF' },
    zh: { title: 'ROI分析报告', inputs: '输入数据', investment: '投资', avgSpend: '平均客单价', newCust: '每月新客户', visits: '每年回访次数', discount: '平均优惠券折扣', redemptions: '每月优惠券兑换', cogs: '商品成本', revenue: '收入分析', monthlyRev: '月收入（新客户）', grossAnnual: '年毛收入', cogsLabel: '商品成本', netAnnual: '年净收入', annualRedemptions: '年兑换量', couponRev: '优惠券收入', couponCost: '优惠券折扣成本', results: '结果', roi: '投资回报率', netProfit: '净利润', generated: '生成于', registerTape: '收银台小票广告', printSave: '打印 / 保存为PDF' },
    vi: { title: 'Báo Cáo Phân Tích ROI', inputs: 'Dữ Liệu', investment: 'Đầu tư', avgSpend: 'Chi tiêu TB/khách', newCust: 'Khách mới / Tháng', visits: 'Lượt ghé / Năm', discount: 'Giảm giá TB/coupon', redemptions: 'Đổi coupon / Tháng', cogs: 'Giá vốn hàng bán', revenue: 'Phân Tích Doanh Thu', monthlyRev: 'Doanh thu tháng (Khách mới)', grossAnnual: 'Tổng doanh thu năm', cogsLabel: 'Giá vốn hàng bán', netAnnual: 'Doanh thu ròng năm', annualRedemptions: 'Đổi coupon hàng năm', couponRev: 'Doanh thu coupon', couponCost: 'Chi phí giảm giá coupon', results: 'Kết Quả', roi: 'Tỷ suất hoàn vốn', netProfit: 'Lợi nhuận ròng', generated: 'Tạo ngày', registerTape: 'Quảng cáo hóa đơn', printSave: 'In / Lưu PDF' },
    tl: { title: 'ROI Analysis Report', inputs: 'Mga Input', investment: 'Puhunan', avgSpend: 'Avg na Gastos ng Customer', newCust: 'Bagong Customer / Buwan', visits: 'Bisita / Taon', discount: 'Avg Diskwento sa Kupon', redemptions: 'Buwanang Kupon', cogs: 'Halaga ng Benta', revenue: 'Pagsusuri ng Kita', monthlyRev: 'Buwanang Kita (Bagong Customer)', grossAnnual: 'Taunang Gross na Kita', cogsLabel: 'Halaga ng Benta', netAnnual: 'Taunang Net na Kita', annualRedemptions: 'Taunang Kupon', couponRev: 'Kita mula sa Kupon', couponCost: 'Gastos sa Diskwento ng Kupon', results: 'Mga Resulta', roi: 'Return on Investment', netProfit: 'Net na Kita', generated: 'Ginawa', registerTape: 'Register Tape Advertising', printSave: 'I-print / I-save bilang PDF' },
    ko: { title: 'ROI 분석 보고서', inputs: '입력 데이터', investment: '투자', avgSpend: '평균 고객 지출', newCust: '월 신규 고객', visits: '연간 방문 횟수', discount: '평균 쿠폰 할인', redemptions: '월간 쿠폰 사용', cogs: '매출원가', revenue: '수익 분석', monthlyRev: '월 수익 (신규 고객)', grossAnnual: '연간 총 수익', cogsLabel: '매출원가', netAnnual: '연간 순 수익', annualRedemptions: '연간 쿠폰 사용', couponRev: '쿠폰 수익', couponCost: '쿠폰 할인 비용', results: '결과', roi: '투자 수익률', netProfit: '순이익', generated: '생성일', registerTape: '영수증 광고', printSave: '인쇄 / PDF 저장' }
  };

  function exportROI(store, lang = 'en') {
    const r = ROI_TRANSLATIONS[lang] || ROI_TRANSLATIONS.en;
    const investment = parseFloat(roiInvestment.replace(/,/g, ''));
    // Use shared canonical ROI formula
    const roiCalc = sharedCalculateROI({
      totalAdCost: investment,
      months: 12,
      redemptions: roiTotalRedemptions || 0,
      newCustomers: roiNewCustomers || 0,
      ticket: roiAvgSpend || 0,
      discount: roiCouponDiscount || 0,
      cogsPercent: roiCOGS || 0,
      visitsPerYear: roiVisitsPerYear || 1,
    });
    const grossRevenue = roiCalc.totalRevenue + roiCalc.totalDiscounts + roiCalc.totalCogs;
    const cogsAmount = roiCalc.totalCogs;
    const annualRevenue = grossRevenue - cogsAmount;
    const annualRedemptions = (roiTotalRedemptions || 0) * 12;
    const couponRevenue = annualRedemptions ? (roiAvgSpend - (roiCouponDiscount || 0)) * annualRedemptions : 0;
    const couponCost = (roiCouponDiscount || 0) * annualRedemptions;
    const couponCOGS = couponRevenue * ((roiCOGS || 0) / 100);
    const totalRevenue = roiCalc.totalRevenue + roiCalc.totalDiscounts;
    const netRevenue = totalRevenue - roiCalc.totalDiscounts;
    const roiPercent = roiCalc.roiPercent;
    const monthlyRevenue = roiCalc.monthlyRevenue;
    const netProfit = roiCalc.campaignProfit;
    const date = new Date().toLocaleDateString();

    const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ROI Report — ${store.GroceryChain} ${store.City}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; max-width: 600px; margin: 0 auto; background: #fff; }
  .header { background: linear-gradient(135deg, #CC0000, #8B0000); color: white; padding: 24px; border-radius: 12px; margin-bottom: 24px; text-align: center; }
  .header h1 { font-size: 22px; margin-bottom: 4px; }
  .header p { font-size: 14px; opacity: 0.9; }
  .section { margin-bottom: 20px; }
  .section h3 { font-size: 15px; color: #666; margin-bottom: 8px; border-bottom: 2px solid #eee; padding-bottom: 4px; }
  .row { display: flex; justify-content: space-between; align-items: center; padding: 10px 12px; background: #f9f9f9; border-radius: 8px; margin-bottom: 6px; }
  .row.highlight { background: #f0fff0; border: 2px solid #2e7d32; }
  .label { font-size: 13px; color: #555; }
  .value { font-size: 16px; font-weight: 700; }
  .green { color: #2e7d32; }
  .red { color: #c33; }
  .big { font-size: 22px; color: #2e7d32; }
  .footer { text-align: center; color: #999; font-size: 12px; margin-top: 30px; padding-top: 16px; border-top: 1px solid #eee; }
  .logo { font-size: 18px; font-weight: 700; color: #CC0000; margin-bottom: 4px; }
  @media print { body { padding: 12px; } .no-print { display: none; } }
</style></head><body>
<div class="header">
  <h1>${r.title}</h1>
  <p>${store.GroceryChain} — ${store.City}, ${store.State}</p>
  <p>Store: ${store.StoreName} | ${date}</p>
</div>

<div class="section">
  <h3>${r.inputs}</h3>
  <div class="row"><span class="label">${r.investment}</span><span class="value">$${investment.toLocaleString()}</span></div>
  <div class="row"><span class="label">${r.avgSpend}</span><span class="value">$${roiAvgSpend}</span></div>
  <div class="row"><span class="label">${r.newCust}</span><span class="value">${roiNewCustomers}</span></div>
  <div class="row"><span class="label">${r.visits}</span><span class="value">${roiVisitsPerYear}</span></div>
  ${roiCouponDiscount ? `<div class="row"><span class="label">${r.discount}</span><span class="value">$${roiCouponDiscount}</span></div>` : ''}
  ${roiTotalRedemptions ? `<div class="row"><span class="label">${r.redemptions}</span><span class="value">${roiTotalRedemptions}</span></div>` : ''}
  ${roiCOGS ? `<div class="row"><span class="label">${r.cogs}</span><span class="value">${roiCOGS}%</span></div>` : ''}
</div>

<div class="section">
  <h3>${r.revenue}</h3>
  <div class="row"><span class="label">${r.monthlyRev}</span><span class="value green">$${monthlyRevenue.toLocaleString()}/mo</span></div>
  <div class="row"><span class="label">${r.grossAnnual}</span><span class="value green">$${grossRevenue.toLocaleString()}</span></div>
  ${roiCOGS ? `<div class="row"><span class="label">${r.cogsLabel} (${roiCOGS}%)</span><span class="value red">-$${cogsAmount.toLocaleString()}</span></div>
  <div class="row"><span class="label">${r.netAnnual}</span><span class="value green">$${annualRevenue.toLocaleString()}</span></div>` : ''}
  ${roiTotalRedemptions ? `<div class="row"><span class="label">${r.annualRedemptions} (${roiTotalRedemptions}/mo x 12)</span><span class="value">${annualRedemptions.toLocaleString()}</span></div>
  <div class="row"><span class="label">${r.couponRev}</span><span class="value green">$${couponRevenue.toLocaleString()}</span></div>
  <div class="row"><span class="label">${r.couponCost}</span><span class="value red">-$${couponCost.toLocaleString()}</span></div>` : ''}
</div>

<div class="section">
  <h3>${r.results}</h3>
  <div class="row highlight"><span class="label">${r.roi}</span><span class="value big">${roiPercent}% ROI</span></div>
  <div class="row"><span class="label">${r.netProfit}</span><span class="value green">$${netProfit.toLocaleString()}</span></div>
</div>

<div class="footer">
  <div class="logo">imPro — IndoorMedia</div>
  <p>${r.generated} ${date} | ${r.registerTape}</p>
</div>

<div class="no-print" style="text-align:center;margin-top:20px;">
  <button onclick="window.print()" style="padding:12px 32px;background:#CC0000;color:white;border:none;border-radius:8px;font-size:16px;cursor:pointer;">${r.printSave}</button>
</div>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const w = window.open(url, '_blank');
    if (!w) {
      // Fallback: download as file
      const a = document.createElement('a');
      a.href = url;
      a.download = `ROI-Report-${store.StoreName}-${new Date().toISOString().slice(0,10)}.html`;
      a.click();
    }
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }

  function shareROI(store) {
    const investment = parseFloat(roiInvestment.replace(/,/g, ''));
    const calcSc = (mult) => {
      const sc = sharedCalculateROI({
        totalAdCost: investment,
        months: 12,
        redemptions: roiTotalRedemptions || 0,
        newCustomers: Math.round((roiNewCustomers || 0) * mult),
        ticket: roiAvgSpend || 0,
        discount: roiCouponDiscount || 0,
        cogsPercent: roiCOGS || 0,
        visitsPerYear: roiVisitsPerYear || 1,
      });
      return { profit: sc.campaignProfit, roi: sc.roiPercent, customers: sc.totalNewCustomers };
    };
    const con = calcSc(0); const bal = calcSc(1); const opt = calcSc(3);

    const text = `📊 ROI Report — ${store.GroceryChain} ${store.City}, ${store.State}
Store: ${store.StoreName}

💰 Investment: $${investment.toLocaleString()}

📊 THREE SCENARIOS:
🟢 Conservative (coupons only): $${con.profit.toLocaleString()} profit / ${con.roi}% ROI
🔵 Balanced (${roiNewCustomers} new/mo): $${bal.profit.toLocaleString()} profit / ${bal.roi}% ROI
🚀 Optimistic (${roiNewCustomers * 3} new/mo): $${opt.profit.toLocaleString()} profit / ${opt.roi}% ROI

*Many shoppers see your ad every visit but never use a coupon — they still become customers.

— IndoorMedia Register Tape Advertising`;

    if (navigator.share) {
      navigator.share({ title: `ROI Report — ${store.GroceryChain}`, text }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text).then(() => alert('📋 ROI report copied to clipboard!')).catch(() => {});
    }
  }

  async function loadStores() {
    try {
      setLoading(true);
      const response = await fetch(import.meta.env.BASE_URL + 'data/stores.json');
      if (!response.ok) throw new Error('Failed to load stores');
      const data = await response.json();
      allStores = data || [];
      console.log(`Loaded ${allStores.length} stores`);
    } catch (err) {
      setError('Failed to load stores: ' + err.message);
    } finally {
      setLoading(false);
    }
  }

  function filterStores() {
    if (!searchTerm.trim()) {
      filtered = [];
      return;
    }

    const term = searchTerm.toLowerCase();
    filtered = allStores.filter(store => 
      (store.StoreName && store.StoreName.toLowerCase().includes(term)) ||
      (store.GroceryChain && store.GroceryChain.toLowerCase().includes(term)) ||
      (store.City && store.City.toLowerCase().includes(term)) ||
      (store.Address && store.Address.toLowerCase().includes(term)) ||
      (store.State && store.State.toLowerCase().includes(term)) ||
      (store.PostalCode && store.PostalCode.includes(term))
    ).slice(0, 50);

    searchResults.set(filtered);
  }

  function findNearby() {
    if (!navigator.geolocation) {
      setError('Geolocation not supported in this browser');
      return;
    }

    setLoading(true);
    navigator.geolocation.getCurrentPosition(
      position => {
        const { latitude, longitude } = position.coords;
        userLocation = { lat: latitude, lng: longitude };
        useGeolocation = true;
        
        // Sort stores by distance, filtering out bad coords
        filtered = smartSortByDistance(latitude, longitude);
        searchTerm = '';
        searchResults.set(filtered);
        setLoading(false);
      },
      (err) => {
        setError('Unable to access location. Please allow location access.');
        setLoading(false);
      },
      { enableHighAccuracy: true, timeout: 10000 }
    );
  }

  async function findByAddress() {
    if (!addressSearch.trim()) return;
    addressSearching = true;
    setLoading(true);
    setError('');

    try {
      // Geocode using Nominatim (free, no API key)
      const q = encodeURIComponent(addressSearch.trim());
      const res = await fetch(`https://nominatim.openstreetmap.org/search?q=${q}&format=json&limit=1&countrycodes=us`, {
        headers: { 'Accept': 'application/json' }
      });
      const data = await res.json();

      if (!data || data.length === 0) {
        setError(`Could not find location for "${addressSearch}". Try a full address, city, or zip code.`);
        setLoading(false);
        addressSearching = false;
        return;
      }

      const lat = parseFloat(data[0].lat);
      const lng = parseFloat(data[0].lon);
      const displayName = data[0].display_name?.split(',').slice(0, 3).join(',') || addressSearch;

      userLocation = { lat, lng };
      useGeolocation = true;

      // Sort stores by distance, filtering out bad coords
      filtered = smartSortByDistance(lat, lng, addressSearch);
      searchTerm = '';
      searchResults.set(filtered);
    } catch (err) {
      setError('Address lookup failed: ' + err.message);
    } finally {
      setLoading(false);
      addressSearching = false;
    }
  }

  // Detect stores with junk coordinates (state centroids shared by >10 stores)
  let _badCoordSet = null;
  function isBadCoord(s) {
    if (!s.latitude || !s.longitude) return true;
    if (!_badCoordSet) {
      const counts = {};
      for (const st of allStores) {
        if (!st.latitude || !st.longitude) continue;
        const key = `${st.latitude.toFixed(4)},${st.longitude.toFixed(4)}`;
        counts[key] = (counts[key] || 0) + 1;
      }
      _badCoordSet = new Set(Object.entries(counts).filter(([, v]) => v > 10).map(([k]) => k));
    }
    return _badCoordSet.has(`${s.latitude.toFixed(4)},${s.longitude.toFixed(4)}`);
  }

  function smartSortByDistance(lat, lng, sourceText = '') {
    const withCoords = [];
    const withoutCoords = [];
    for (const s of allStores) {
      if (!isBadCoord(s)) {
        withCoords.push({ ...s, _dist: calcDistance(lat, lng, s.latitude, s.longitude) });
      } else {
        withoutCoords.push(s);
      }
    }
    withCoords.sort((a, b) => a._dist - b._dist);
    let results = withCoords.slice(0, 30);

    // Supplement with city-matched stores that have bad coords
    if (withoutCoords.length > 0) {
      const refCity = results.length > 0 ? results[0].City?.toLowerCase() : sourceText.toLowerCase();
      const cityMatches = withoutCoords.filter(s => {
        const city = (s.City || '').toLowerCase();
        return refCity && (city.includes(refCity) || refCity.includes(city));
      });
      for (const s of cityMatches) {
        if (!results.find(r => r.StoreName === s.StoreName)) {
          results.push({ ...s, _dist: undefined });
        }
      }
    }
    return results.slice(0, 40);
  }

  function calcDistance(lat1, lon1, lat2, lon2) {
    const R = 3959; // Earth radius in miles
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = 
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c;
  }

  // Track expanded cards, ad type, and co-op unlock
  let expandedStore = null;
  let adType = {}; // { storeName: 'single' | 'double' }
  let coopUnlocked = {}; // { storeName: true/false }

  function toggleExpand(storeName) {
    expandedStore = expandedStore === storeName ? null : storeName;
    if (!adType[storeName]) adType[storeName] = 'single';
    // Lookup phone number when expanding
    if (expandedStore === storeName) {
      const store = filtered.find(s => s.StoreName === storeName) || allStores.find(s => s.StoreName === storeName);
      if (store) lookupStorePhone(store);
    }
  }

  function toggleAdType(storeName) {
    adType[storeName] = adType[storeName] === 'single' ? 'double' : 'single';
    adType = adType; // trigger reactivity
  }

  function unlockCoop(storeName) {
    coopUnlocked[storeName] = !coopUnlocked[storeName];
    coopUnlocked = coopUnlocked; // trigger reactivity
  }

  // Payment plan calculations
  // Standard = base + $1,200 pad + $125 production
  // Co-Op = base + $125 production (no pad)
  function calcPricing(basePrice, isCoop = false) {
    const prod = 125;
    const pad = isCoop ? 0 : 1200;
    const total = basePrice + pad + prod;
    return {
      monthly: (total / 12).toFixed(2),
      monthlyTotal: total.toFixed(2),
      threeMonth: (((( basePrice + pad) * 0.90) + prod) / 3).toFixed(2),
      threeMonthTotal: ((( basePrice + pad) * 0.90) + prod).toFixed(2),
      sixMonth: ((((basePrice + pad) * 0.925) + prod) / 6).toFixed(2),
      sixMonthTotal: (((basePrice + pad) * 0.925) + prod).toFixed(2),
      pif: (((basePrice + pad) * 0.85) + prod).toFixed(2),
      savings: ((basePrice + pad) * 0.15).toFixed(2)
    };
  }

  let addedToCartMsg = '';

  function handleAddToCart(store, selectedAdType, plan) {
    const isCoop = coopUnlocked[store.StoreName] || false;
    const base = selectedAdType === 'double' ? store.DoubleAd : store.SingleAd;
    const pricing = calcPricing(base, isCoop);
    
    const planNames = {
      monthly: 'Monthly (12 payments)',
      threeMonth: '3-Month (10% off)',
      sixMonth: '6-Month (7.5% off)',
      pif: 'Paid-in-Full (15% off)'
    };

    const priceDisplay = {
      monthly: `$${pricing.monthly}/mo × 12 = $${pricing.monthlyTotal}`,
      threeMonth: `$${pricing.threeMonth} × 3 = $${pricing.threeMonthTotal}`,
      sixMonth: `$${pricing.sixMonth} × 6 = $${pricing.sixMonthTotal}`,
      pif: `$${pricing.pif}`
    };

    const item = {
      id: Date.now(),
      name: `Register Tape — ${isCoop ? 'Co-Op' : 'Standard'}`,
      emoji: '🧾',
      store: `${store.GroceryChain} - ${store.City}`,
      storeNum: store.StoreName,
      storeAddress: store.Address || '',
      storeCycle: store.Cycle || '',
      plan: `${selectedAdType === 'double' ? 'Double' : 'Single'} Ad — ${planNames[plan]}`,
      price: priceDisplay[plan],
      addedAt: new Date().toISOString(),
    };

    // Save to localStorage (same format as Cart.svelte)
    try {
      const cart = JSON.parse(localStorage.getItem('indoormedia_cart') || '[]');
      cart.push(item);
      localStorage.setItem('indoormedia_cart', JSON.stringify(cart));
      addedToCartMsg = `✅ Added ${store.GroceryChain} - ${store.City}`;
      setTimeout(() => { addedToCartMsg = ''; }, 2500);
    } catch (err) {
      console.error('Failed to add to cart:', err);
    }
  }

  onMount(loadStores);
</script>

<div class="search-container">
  <h2>🏪 Store Network</h2>
  <p class="subtitle">Find pricing and delivery info for 7,835+ stores nationwide</p>

  <div class="search-box">
    <input
      type="text"
      placeholder="Search by store name, city, zip code, or number..."
      bind:value={searchTerm}
      on:input={filterStores}
      disabled={$loading}
    />
    {#if $loading}
      <div class="spinner"></div>
    {/if}
  </div>

  <div class="address-search-box">
    <input
      type="text"
      placeholder="Enter any address, city, or zip to find closest stores..."
      bind:value={addressSearch}
      on:keydown={(e) => { if (e.key === 'Enter') findByAddress(); }}
      disabled={$loading}
    />
    <button
      class="address-btn"
      on:click={findByAddress}
      disabled={$loading || !addressSearch.trim()}
    >
      {addressSearching ? '⏳' : '📍'} Find Closest
    </button>
  </div>

  <div class="location-toggle">
    <button
      class="geo-btn"
      on:click={findNearby}
      disabled={$loading}
    >
      📍 Use My Location
    </button>
    {#if useGeolocation && userLocation}
      <span class="location-indicator">Showing closest stores</span>
    {/if}
  </div>

  <div class="cycle-filter">
    <button class="cycle-btn" class:active={storeCycleFilter === 'all'} on:click={() => storeCycleFilter = 'all'}>All</button>
    <button class="cycle-btn" class:active={storeCycleFilter === 'A'} on:click={() => storeCycleFilter = 'A'}>Cycle A</button>
    <button class="cycle-btn" class:active={storeCycleFilter === 'B'} on:click={() => storeCycleFilter = 'B'}>Cycle B</button>
    <button class="cycle-btn" class:active={storeCycleFilter === 'C'} on:click={() => storeCycleFilter = 'C'}>Cycle C</button>
  </div>

  {#if $error}
    <div class="error-box">{$error}</div>
  {/if}

  <div class="results">
    {#if $loading}
      <p class="loading">Loading stores...</p>
    {:else if filtered.length === 0 && searchTerm}
      <p class="no-results">
        <span style="font-size: 2rem; margin-bottom: 1rem; display: block;">🔍</span>
        No stores found for "{searchTerm}"<br/>
        <span style="font-size: 0.9rem; color: #999; margin-top: 0.5rem; display: block;">Try searching by:</span>
        <span style="font-size: 0.85rem; color: #999;">Store #, City, Chain, or Address</span>
      </p>
    {:else if filtered.length === 0}
      <p class="hint">Start typing to search for stores</p>
    {:else}
      <div class="store-grid">
        {#each filtered.filter(s => storeCycleFilter === 'all' || s.Cycle === storeCycleFilter) as store (store.StoreName)}
          {@const currentAdType = adType[store.StoreName] || 'single'}
          {@const basePrice = currentAdType === 'double' ? store.DoubleAd : store.SingleAd}
          {@const isCoop = coopUnlocked[store.StoreName] || false}
          {@const stdPricing = calcPricing(basePrice, false)}
          {@const coopPricing = calcPricing(basePrice, true)}
          {@const pricing = isCoop ? coopPricing : stdPricing}
          {@const isExpanded = expandedStore === store.StoreName}
          <div class="store-card" class:expanded={isExpanded} class:coop-active={isCoop}>
            <div class="store-header" on:click={() => toggleExpand(store.StoreName)}>
              <div>
                <h3>{store.GroceryChain}</h3>
                <span class="store-number">{store.StoreName}</span>
              </div>
              <span class="expand-icon">{isExpanded ? '▲' : '▼'}</span>
            </div>
            <div class="store-info">
              <p class="address">{store.Address}</p>
              <p class="city">{store.City}, {store.State} {store.PostalCode}</p>
              {#if storePhones[store.StoreName] && storePhones[store.StoreName] !== 'loading'}
                <p class="store-phone"><a href="tel:{storePhones[store.StoreName]}">📞 {storePhones[store.StoreName]}</a></p>
              {:else if storePhones[store.StoreName] === 'loading'}
                <p class="store-phone" style="color: var(--text-secondary, #999);">📞 Looking up...</p>
              {/if}
              <p class="cycle">Cycle: {store.Cycle} | Cases: {store['Case Count']}{store.InstallDay ? ` | In Stores: ${store.InstallDay}${store.InstallDay == 1 || store.InstallDay == 21 || store.InstallDay == 31 ? 'st' : store.InstallDay == 2 || store.InstallDay == 22 ? 'nd' : store.InstallDay == 3 || store.InstallDay == 23 ? 'rd' : 'th'}` : ''}</p>
              {#if useGeolocation && userLocation && store.latitude && store.longitude}
                <p class="distance">
                  📍 {(calcDistance(userLocation.lat, userLocation.lng, store.latitude, store.longitude)).toFixed(1)} mi away
                </p>
              {/if}
            </div>

            <!-- Ad Type Toggle -->
            <div class="ad-toggle">
              <button
                class="ad-btn"
                class:active={currentAdType === 'single'}
                on:click={() => { adType[store.StoreName] = 'single'; adType = adType; }}
              >Single Ad</button>
              <button
                class="ad-btn"
                class:active={currentAdType === 'double'}
                on:click={() => { adType[store.StoreName] = 'double'; adType = adType; }}
              >Double Ad</button>
            </div>

            <!-- Standard Pricing (always visible) -->
            <div class="pricing-label">{isCoop ? '🤝 Co-Op Pricing' : '💼 Standard Pricing'}</div>
            <div class="pricing">
              <div class="price-row">
                <span class="price-label">Monthly</span>
                <span class="price-value">${pricing.monthly}/mo × 12 = ${pricing.monthlyTotal}</span>
              </div>
              <div class="price-row highlight">
                <span class="price-label">Paid in Full</span>
                <span class="price-value pif">${pricing.pif} (15% off)</span>
              </div>
            </div>

            <!-- Co-Op Unlock Button -->
            <button
              class="coop-btn"
              class:unlocked={isCoop}
              on:click={() => unlockCoop(store.StoreName)}
            >
              {isCoop ? '🔓 Showing Co-Op Pricing — Tap to Reset' : '🔒 Manager Approved Co-Op'}
            </button>

            <!-- Expanded: All 4 Payment Plans -->
            {#if isExpanded}
              <div class="expanded-pricing">
                <!-- Ad Type Toggle in Expanded View -->
                <div class="expanded-ad-toggle">
                  <button
                    class="ad-btn"
                    class:active={currentAdType === 'single'}
                    on:click={() => { adType[store.StoreName] = 'single'; adType = adType; }}
                  >Single Ad</button>
                  <button
                    class="ad-btn"
                    class:active={currentAdType === 'double'}
                    on:click={() => { adType[store.StoreName] = 'double'; adType = adType; }}
                  >Double Ad</button>
                </div>

                <!-- Impressions -->
                {#if true}
                {@const caseCount = parseInt(store['Case Count']) || 0}
                {@const annualImpressions = caseCount * 50 * 137 * 2 * 4}
                {@const monthlyImpressions = Math.round(annualImpressions / 12)}
                {@const dailyImpressions = Math.round(annualImpressions / 365)}
                {#if caseCount > 0}
                  <div class="impressions-card">
                    <div class="impressions-title">👁️ Estimated Ad Impressions</div>
                    <div class="impressions-grid">
                      <div class="imp-stat"><span class="imp-value">{dailyImpressions.toLocaleString()}</span><span class="imp-label">Daily</span></div>
                      <div class="imp-stat"><span class="imp-value">{monthlyImpressions.toLocaleString()}</span><span class="imp-label">Monthly</span></div>
                      <div class="imp-stat highlight"><span class="imp-value">{annualImpressions.toLocaleString()}</span><span class="imp-label">Annual</span></div>
                    </div>
                    <div class="imp-formula">{caseCount} cases × 50 rolls × 137 segments × 2 prints per segment × 4 quarters</div>
                  </div>
                {/if}
                {/if}

                <h4>All Payment Plans — {currentAdType === 'double' ? 'Double' : 'Single'} Ad {isCoop ? '(Co-Op)' : '(Standard)'}</h4>
                
                <div class="plan-card" on:click={() => handleAddToCart(store, currentAdType, 'monthly')}>
                  <div class="plan-header">
                    <span class="plan-name">📅 Monthly</span>
                    <span class="plan-badge">12 payments</span>
                  </div>
                  <div class="plan-price">${pricing.monthly}<span class="per">/month</span></div>
                  <div class="plan-total">Total: ${pricing.monthlyTotal}</div>
                  <div class="plan-daily">That's just <strong>${(parseFloat(pricing.monthlyTotal) / 365).toFixed(2)}/day</strong></div>
                  <button class="roi-btn" on:click|stopPropagation={() => showROI(pricing.monthlyTotal, store)}>📊 ROI Calculator</button>
                </div>

                <div class="plan-card" on:click={() => handleAddToCart(store, currentAdType, 'threeMonth')}>
                  <div class="plan-header">
                    <span class="plan-name">📦 3-Month</span>
                    <span class="plan-badge save">Save 10%</span>
                  </div>
                  <div class="plan-price">${pricing.threeMonth}<span class="per"> × 3</span></div>
                  <div class="plan-total">Total: ${pricing.threeMonthTotal}</div>
                  <div class="plan-daily">That's just <strong>${(parseFloat(pricing.threeMonthTotal) / 365).toFixed(2)}/day</strong></div>
                  <button class="roi-btn" on:click|stopPropagation={() => showROI(pricing.threeMonthTotal, store)}>📊 ROI Calculator</button>
                </div>

                <div class="plan-card" on:click={() => handleAddToCart(store, currentAdType, 'sixMonth')}>
                  <div class="plan-header">
                    <span class="plan-name">📦 6-Month</span>
                    <span class="plan-badge save">Save 7.5%</span>
                  </div>
                  <div class="plan-price">${pricing.sixMonth}<span class="per"> × 6</span></div>
                  <div class="plan-total">Total: ${pricing.sixMonthTotal}</div>
                  <div class="plan-daily">That's just <strong>${(parseFloat(pricing.sixMonthTotal) / 365).toFixed(2)}/day</strong></div>
                  <button class="roi-btn" on:click|stopPropagation={() => showROI(pricing.sixMonthTotal, store)}>📊 ROI Calculator</button>
                </div>

                <div class="plan-card best" on:click={() => handleAddToCart(store, currentAdType, 'pif')}>
                  <div class="plan-header">
                    <span class="plan-name">⭐ Paid in Full</span>
                    <span class="plan-badge best-badge">Best Deal — 15% off</span>
                  </div>
                  <div class="plan-price">${pricing.pif}</div>
                  <div class="plan-total">One payment — Save ${pricing.savings}</div>
                  <div class="plan-daily">That's just <strong>${(parseFloat(pricing.pif) / 365).toFixed(2)}/day</strong></div>
                  <button class="roi-btn" on:click|stopPropagation={() => showROI(pricing.pif, store)}>📊 ROI Calculator</button>
                </div>

                <p class="tap-hint">Tap a plan to add to quote</p>

                <!-- Export pricing sheet -->
                <div class="export-section">
                  <button class="export-btn" on:click|stopPropagation={() => exportPricingSheet(store, pricing, currentAdType, 'en')}>📄 Export Pricing Sheet</button>
                  <div class="lang-btns">
                    <button class="lang-btn" on:click|stopPropagation={() => exportPricingSheet(store, pricing, currentAdType, 'es')}>🇪🇸 Español</button>
                    <button class="lang-btn" on:click|stopPropagation={() => exportPricingSheet(store, pricing, currentAdType, 'zh')}>🇨🇳 中文</button>
                    <button class="lang-btn" on:click|stopPropagation={() => exportPricingSheet(store, pricing, currentAdType, 'vi')}>🇻🇳 Tiếng Việt</button>
                    <button class="lang-btn" on:click|stopPropagation={() => exportPricingSheet(store, pricing, currentAdType, 'tl')}>🇵🇭 Tagalog</button>
                    <button class="lang-btn" on:click|stopPropagation={() => exportPricingSheet(store, pricing, currentAdType, 'ko')}>🇰🇷 한국어</button>
                  </div>
                </div>

                <!-- ROI Calculator -->
                {#if roiStore === store.StoreName}
                  <div class="roi-calculator">
                    <h4>📊 ROI Calculator</h4>
                    <p class="roi-subtitle">Investment: <strong>${roiInvestment}</strong></p>
                    
                    <div class="roi-field">
                      <label>Average Customer Spend ($)</label>
                      <input type="number" bind:value={roiAvgSpend} placeholder="50" />
                    </div>
                    
                    <div class="roi-field">
                      <label>New Customers per Month</label>
                      <input type="number" bind:value={roiNewCustomers} placeholder="10" />
                    </div>
                    
                    <div class="roi-field">
                      <label>Visits per Year (per customer)</label>
                      <input type="number" bind:value={roiVisitsPerYear} placeholder="12" />
                    </div>

                    <div class="roi-field">
                      <label>Avg Discount per Coupon ($)</label>
                      <input type="number" bind:value={roiCouponDiscount} placeholder="0" />
                    </div>

                    <div class="roi-field">
                      <label>Monthly Coupon Redemptions</label>
                      <input type="number" bind:value={roiTotalRedemptions} placeholder="0" />
                    </div>

                    <div class="roi-field">
                      <label>Cost of Goods Sold (%)</label>
                      <input type="number" bind:value={roiCOGS} placeholder="0" min="0" max="100" />
                    </div>

                    {#if roiAvgSpend && roiNewCustomers}
                      {@const investment = parseFloat(roiInvestment.replace(/,/g, ''))}
                      {@const cogsRate = (roiCOGS || 0) / 100}
                      {@const annualRedemptions = (roiTotalRedemptions || 0) * 12}
                      {@const couponCost = (roiCouponDiscount || 0) * annualRedemptions}
                      {@const scenarioCalc = (custMultiplier) => {
                        const customers = Math.round(roiNewCustomers * custMultiplier);
                        const custRevenue = roiAvgSpend * customers * 12 * (roiVisitsPerYear || 1);
                        const custCogs = custRevenue * cogsRate;
                        const couponRev = annualRedemptions ? (roiAvgSpend - (roiCouponDiscount || 0)) * annualRedemptions : 0;
                        const couponCogs = couponRev * cogsRate;
                        const totalRev = custRevenue - custCogs + couponRev - couponCogs - couponCost;
                        const profit = totalRev - investment;
                        const roi = ((profit / investment) * 100).toFixed(0);
                        return { customers, totalRev: Math.round(totalRev), profit: Math.round(profit), roi, totalNewCustomers: customers * 12 };
                      }}
                      {@const conservative = scenarioCalc(0)}
                      {@const balanced = scenarioCalc(1)}
                      {@const optimistic = scenarioCalc(3)}
                      {@const monthlyRevenue = roiAvgSpend * roiNewCustomers * (roiVisitsPerYear || 1)}
                      
                      <div class="roi-results">
                        <div class="roi-result-card">
                          <span class="roi-label">Monthly Revenue (Balanced)</span>
                          <span class="roi-value green">${monthlyRevenue.toLocaleString()}/mo</span>
                        </div>
                        <div class="roi-result-card highlight">
                          <span class="roi-label">Return on Investment (Balanced)</span>
                          <span class="roi-value big">{balanced.roi}% ROI</span>
                        </div>
                        <div class="roi-result-card">
                          <span class="roi-label">Net Profit (Balanced)</span>
                          <span class="roi-value green">${balanced.profit.toLocaleString()}</span>
                        </div>
                      </div>

                      <div class="scenario-section">
                        <h5>📊 Three Scenarios</h5>
                        <p class="scenario-hint">Many shoppers see your ad but never use a coupon — they still become customers.</p>
                        <div class="scenario-row">
                          <div class="scenario-box conservative">
                            <div class="sc-label">🟢 Conservative</div>
                            <div class="sc-desc">Coupons only</div>
                            <div class="sc-profit">${conservative.profit.toLocaleString()}</div>
                            <div class="sc-roi">{conservative.roi}% ROI</div>
                          </div>
                          <div class="scenario-box balanced">
                            <div class="sc-label">🔵 Balanced</div>
                            <div class="sc-desc">{balanced.customers} new/mo</div>
                            <div class="sc-profit">${balanced.profit.toLocaleString()}</div>
                            <div class="sc-roi">{balanced.roi}% ROI</div>
                          </div>
                          <div class="scenario-box optimistic">
                            <div class="sc-label">🚀 Optimistic</div>
                            <div class="sc-desc">{optimistic.customers} new/mo</div>
                            <div class="sc-profit">${optimistic.profit.toLocaleString()}</div>
                            <div class="sc-roi">{optimistic.roi}% ROI</div>
                          </div>
                        </div>
                      </div>
                    {/if}

                    <div class="roi-action-btns">
                      <button class="roi-export-btn" on:click={() => exportROI(store)}>📄 Export Report</button>
                      <button class="roi-share-btn" on:click={() => shareROI(store)}>📤 Share</button>
                    </div>
                    <div class="lang-btns" style="margin-top:8px;">
                      <button class="lang-btn" on:click={() => exportROI(store, 'es')}>🇪🇸 Español</button>
                      <button class="lang-btn" on:click={() => exportROI(store, 'zh')}>🇨🇳 中文</button>
                      <button class="lang-btn" on:click={() => exportROI(store, 'vi')}>🇻🇳 Tiếng Việt</button>
                      <button class="lang-btn" on:click={() => exportROI(store, 'tl')}>🇵🇭 Tagalog</button>
                      <button class="lang-btn" on:click={() => exportROI(store, 'ko')}>🇰🇷 한국어</button>
                    </div>
                    <button class="roi-close-btn" on:click={() => { roiStore = null; }}>Close Calculator</button>
                  </div>
                {/if}
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>

  {#if addedToCartMsg}
    <div class="cart-toast">{addedToCartMsg}</div>
  {/if}
</div>

<style>
  .search-container {
    max-width: 1200px;
    margin: 0 auto;
  }

  h2 {
    margin: 0 0 0.5rem 0;
    font-size: 24px;
    font-weight: 700;
    color: var(--text-primary);
  }

  .subtitle {
    margin: 0 0 20px 0;
    font-size: 14px;
    color: var(--text-secondary);
  }

  .address-search-box {
    display: flex;
    gap: 8px;
    margin-bottom: 12px;
  }

  .address-search-box input {
    flex: 1;
  }

  .address-btn {
    padding: 12px 16px;
    background: #CC0000;
    color: white;
    border: none;
    border-radius: 8px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    white-space: nowrap;
  }

  .address-btn:hover { background: #990000; }
  .address-btn:disabled { background: #ccc; cursor: not-allowed; }

  .search-box {
    position: relative;
    margin-bottom: 20px;
  }

  input {
    width: 100%;
    padding: 14px 16px;
    border: 2px solid #ddd;
    border-radius: 8px;
    font-size: 16px;
    font-family: inherit;
    transition: border-color 0.3s;
  }

  input:focus {
    outline: none;
    border-color: #CC0000;
    box-shadow: 0 0 0 3px rgba(255, 107, 53, 0.1);
  }

  input:disabled {
    background: #f5f5f5;
    cursor: not-allowed;
  }

  .spinner {
    position: absolute;
    right: 14px;
    top: 50%;
    transform: translateY(-50%);
    width: 18px;
    height: 18px;
    border: 2px solid #f0f0f0;
    border-top-color: #CC0000;
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    to { transform: translateY(-50%) rotate(360deg); }
  }

  .location-toggle {
    display: flex;
    gap: 12px;
    align-items: center;
    margin-bottom: 16px;
  }

  .geo-btn {
    padding: 8px 14px;
    background: white;
    border: 2px solid #CC0000;
    color: #CC0000;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 500;
    font-size: 13px;
    transition: all 0.2s;
  }

  .geo-btn:hover:not(:disabled) {
    background: #fff0f0;
  }

  .geo-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .location-indicator {
    font-size: 12px;
    color: #666;
    padding: 0 8px;
  }

  .error-box {
    background: #ffe0e0;
    color: #c33;
    padding: 12px;
    border-radius: 6px;
    margin-bottom: 16px;
    font-size: 14px;
  }

  .results {
    min-height: 200px;
  }

  .loading, .no-results, .hint {
    text-align: center;
    color: #999;
    padding: 40px 20px;
    font-size: 14px;
  }

  .store-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 16px;
  }

  .store-card {
    background: white;
    border-radius: 8px;
    padding: 16px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    transition: all 0.2s;
  }

  .store-card:hover {
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12);
    transform: translateY(-2px);
  }

  .store-header h3 {
    margin: 0;
    font-size: 16px;
    color: #1a1a1a;
    flex: 1;
  }

  .store-number {
    background: #f5f5f5;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    color: #666;
    font-weight: 500;
    white-space: nowrap;
    margin-left: 8px;
  }

  .store-info {
    margin-bottom: 12px;
  }

  .store-phone a { color: #1565C0; text-decoration: none; font-weight: 600; }
  .store-info p {
    margin: 4px 0;
    font-size: 14px;
    color: #666;
  }

  .city {
    font-weight: 500;
    color: #333;
  }

  .distance {
    color: #CC0000;
    font-weight: 500;
    font-size: 13px;
  }

  .pricing {
    background: #f8f9fa;
    border-radius: 6px;
    padding: 10px;
    margin-bottom: 12px;
  }

  .price-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 4px 0;
    font-size: 13px;
  }

  .price-row.highlight {
    border-top: 1px solid #e0e0e0;
    padding-top: 8px;
    margin-top: 4px;
  }

  .price-label {
    color: #666;
    font-weight: 500;
  }

  .price-value {
    color: #333;
    font-weight: 600;
  }

  .price-value.pif {
    color: #CC0000;
    font-weight: 700;
  }

  .address {
    font-size: 13px !important;
  }

  .cycle {
    font-size: 12px !important;
    color: #999 !important;
  }

  .store-header {
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: start;
    margin-bottom: 12px;
  }

  .expand-icon {
    color: #999;
    font-size: 12px;
    padding: 4px;
  }

  .store-card.expanded {
    border: 2px solid #CC0000;
  }

  /* Ad Type Toggle */
  .ad-toggle {
    display: flex;
    gap: 8px;
    margin-bottom: 12px;
  }

  .ad-btn {
    flex: 1;
    padding: 8px;
    border: 2px solid #ddd;
    background: white;
    border-radius: 6px;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .ad-btn.active {
    border-color: #CC0000;
    background: #CC0000;
    color: white;
  }

  /* Expanded Pricing */
  .expanded-pricing {
    margin-top: 16px;
    padding-top: 16px;
    border-top: 2px solid #eee;
  }

  .expanded-ad-toggle {
    display: flex;
    gap: 8px;
    margin-bottom: 16px;
  }

  .expanded-pricing h4 {
    margin: 0 0 12px 0;
    font-size: 14px;
    color: #333;
    text-align: center;
  }

  .plan-card {
    background: #f8f9fa;
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    padding: 12px;
    margin-bottom: 8px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .plan-card:hover {
    border-color: #CC0000;
    background: #fff5f5;
  }

  .plan-card.best {
    border-color: #CC0000;
    background: #fff0f0;
  }

  .plan-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 4px;
  }

  .plan-name {
    font-weight: 600;
    font-size: 14px;
    color: #333;
  }

  .plan-badge {
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 10px;
    background: #e0e0e0;
    color: #666;
  }

  .plan-badge.save {
    background: #e8f5e9;
    color: #2e7d32;
  }

  .plan-badge.best-badge {
    background: #CC0000;
    color: white;
    font-weight: 600;
  }

  .plan-price {
    font-size: 24px;
    font-weight: 700;
    color: #1a1a1a;
    margin: 4px 0;
  }

  .plan-price .per {
    font-size: 14px;
    font-weight: 400;
    color: #666;
  }

  .plan-total {
    font-size: 13px;
    color: #666;
  }
  .plan-daily {
    font-size: 12px;
    color: #2E7D32;
    margin-top: 4px;
    padding: 4px 8px;
    background: #E8F5E9;
    border-radius: 6px;
    display: inline-block;
  }
  .impressions-card { padding: 14px; margin-bottom: 14px; background: linear-gradient(135deg, #E3F2FD, #F3E5F5); border-radius: 12px; border: 1px solid #1565C0; }
  .impressions-title { font-size: 14px; font-weight: 800; color: #1565C0; margin-bottom: 10px; }
  .impressions-grid { display: flex; gap: 8px; }
  .imp-stat { flex: 1; text-align: center; padding: 8px 4px; background: rgba(255,255,255,0.8); border-radius: 8px; }
  .imp-stat.highlight { background: #1565C0; }
  .imp-stat.highlight .imp-value, .imp-stat.highlight .imp-label { color: white; }
  .imp-value { font-size: 16px; font-weight: 800; display: block; color: #1565C0; }
  .imp-label { font-size: 10px; color: #666; text-transform: uppercase; font-weight: 600; }
  .imp-formula { font-size: 10px; color: #888; margin-top: 6px; text-align: center; }
  .export-section { margin-top: 12px; padding-top: 12px; border-top: 1px solid var(--border-color, #eee); }
  .export-btn { width: 100%; padding: 12px; background: #CC0000; color: white; border: none; border-radius: 10px; font-size: 14px; font-weight: 700; cursor: pointer; margin-bottom: 8px; }
  .lang-btns { display: flex; flex-wrap: wrap; gap: 6px; }
  .lang-btn { flex: 1; min-width: 80px; padding: 8px 6px; border: 1px solid var(--border-color, #ddd); border-radius: 8px; background: var(--card-bg, white); font-size: 11px; font-weight: 600; cursor: pointer; text-align: center; color: var(--text-primary); }

  .pricing-label {
    font-size: 12px;
    font-weight: 600;
    color: #666;
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .coop-btn {
    width: 100%;
    padding: 10px;
    margin-top: 10px;
    border: 1px dashed #999;
    background: #f5f5f5;
    border-radius: 8px;
    cursor: pointer;
    font-size: 13px;
    font-weight: 600;
    color: #666;
    transition: all 0.2s;
    min-height: 44px;
    box-sizing: border-box;
  }

  .coop-btn:hover {
    border-color: #CC0000;
    color: #CC0000;
    background: #fff5f5;
  }

  .coop-btn.unlocked {
    border: 1px solid #2e7d32;
    background: #e8f5e9;
    color: #2e7d32;
  }

  .store-card.coop-active {
    border: 2px solid #2e7d32;
  }

  .tap-hint {
    text-align: center;
    font-size: 12px;
    color: #999;
    margin-top: 8px;
  }

  .add-btn {
    width: 100%;
    padding: 10px;
    background: #CC0000;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 600;
    font-size: 14px;
    transition: background 0.2s;
  }

  .add-btn:hover {
    background: #990000;
  }

  .roi-btn {
    width: 100%;
    margin-top: 8px;
    padding: 8px;
    background: #f0f0f0;
    color: #CC0000;
    border: 2px solid #CC0000;
    border-radius: 6px;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .roi-btn:hover {
    background: #CC0000;
    color: white;
  }

  .scenario-section { margin-top: 14px; }
  .scenario-section h5 { font-size: 14px; margin: 0 0 4px; color: var(--text-primary); }
  .scenario-hint { font-size: 11px; color: var(--text-secondary, #888); margin: 0 0 10px; font-style: italic; }
  .scenario-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }
  .scenario-box { padding: 10px; border-radius: 8px; text-align: center; border: 2px solid var(--border-color, #e0e0e0); background: var(--card-bg, white); }
  .scenario-box.conservative { border-color: #43A047; }
  .scenario-box.balanced { border-color: #1565C0; }
  .scenario-box.optimistic { border-color: #E65100; }
  .sc-label { font-size: 12px; font-weight: 800; }
  .scenario-box.conservative .sc-label { color: #43A047; }
  .scenario-box.balanced .sc-label { color: #1565C0; }
  .scenario-box.optimistic .sc-label { color: #E65100; }
  .sc-desc { font-size: 10px; color: var(--text-secondary, #888); margin-bottom: 6px; }
  .sc-profit { font-size: 16px; font-weight: 800; color: #2E7D32; }
  .sc-roi { font-size: 12px; font-weight: 700; color: var(--text-secondary, #666); }
  .roi-calculator {
    background: #f9f9f9;
    border: 2px solid #CC0000;
    border-radius: 12px;
    padding: 16px;
    margin-top: 16px;
  }

  .roi-calculator h4 {
    margin: 0 0 4px;
    color: #333;
    font-size: 16px;
  }

  .roi-subtitle {
    margin: 0 0 16px;
    color: #666;
    font-size: 14px;
  }

  .roi-field {
    margin-bottom: 12px;
  }

  .roi-field label {
    display: block;
    font-size: 13px;
    font-weight: 600;
    color: #333;
    margin-bottom: 4px;
  }

  .roi-field input {
    width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
    box-sizing: border-box;
  }

  .roi-field input:focus {
    outline: none;
    border-color: #CC0000;
    box-shadow: 0 0 0 2px rgba(204, 0, 0, 0.1);
  }

  .roi-results {
    margin-top: 16px;
    display: grid;
    gap: 8px;
  }

  .roi-result-card {
    background: white;
    border-radius: 8px;
    padding: 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border: 1px solid #eee;
  }

  .roi-result-card.highlight {
    background: #f0fff0;
    border: 2px solid #2e7d32;
  }

  .roi-label {
    font-size: 13px;
    color: #555;
  }

  .roi-value {
    font-size: 16px;
    font-weight: 700;
    color: #333;
  }

  .roi-value.green {
    color: #2e7d32;
  }

  .roi-value.big {
    font-size: 20px;
    color: #2e7d32;
  }

  .roi-action-btns {
    display: flex;
    gap: 8px;
    margin-top: 12px;
  }

  .roi-export-btn, .roi-share-btn {
    flex: 1;
    padding: 10px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .roi-export-btn {
    background: #CC0000;
    color: white;
  }

  .roi-export-btn:hover {
    background: #a00;
  }

  .roi-share-btn {
    background: #2e7d32;
    color: white;
  }

  .roi-share-btn:hover {
    background: #1b5e20;
  }

  .roi-close-btn {
    width: 100%;
    margin-top: 12px;
    padding: 10px;
    background: #999;
    color: white;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    cursor: pointer;
  }

  .roi-close-btn:hover {
    background: #777;
  }

  .cycle-filter {
    display: flex;
    gap: 8px;
    margin-bottom: 16px;
  }

  .cycle-btn {
    flex: 1;
    padding: 10px;
    border: 2px solid #ddd;
    border-radius: 8px;
    background: white;
    font-size: 13px;
    font-weight: 600;
    color: #666;
    cursor: pointer;
    transition: all 0.2s;
  }

  .cycle-btn.active {
    background: #CC0000;
    color: white;
    border-color: #CC0000;
  }

  .cycle-btn:hover:not(.active) {
    border-color: #CC0000;
    color: #CC0000;
  }

  .cart-toast {
    position: fixed;
    bottom: 80px;
    left: 50%;
    transform: translateX(-50%);
    background: #2e7d32;
    color: white;
    padding: 12px 24px;
    border-radius: 8px;
    font-size: 14px;
    font-weight: 600;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
    z-index: 1000;
    animation: slideUp 0.3s ease-out;
  }

  @keyframes slideUp {
    from { transform: translateX(-50%) translateY(20px); opacity: 0; }
    to { transform: translateX(-50%) translateY(0); opacity: 1; }
  }

  @media (max-width: 640px) {
    .store-grid {
      grid-template-columns: 1fr;
    }
  }
</style>
